/*
 Sifer Aseph
 Project Euler
 
 Problem 2 "Even Fibonacci numbers"
 "Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms."
 */

// compiled with -W

#include <iostream>

long evenFibonacci(long);

int main() {
  std::cout << evenFibonacci(33) << std::endl;
  
  return 0;
}

long evenFibonacci(long n) {
  int n1 = 0, n2 = 1, total = 0, i = 0;
  
  for (; i < n; i++) {
    int tmp = n1 + n2;
    n1 = n2;
    n2 = tmp;
    
    if (n2%2 == 0) {
      total += n2;
    }
  }
  
  return total;
}
